apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-probes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-probes-demo
  template:
    metadata:
      labels:
        app: python-probes-demo
    spec:
      containers:
      - name: python-app
        image: 426192960096.dkr.ecr.us-east-1.amazonaws.com/argocdapplication:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        # STARTUP PROBE (correct)
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 10
          periodSeconds: 5

        # READINESS PROBE (correct)
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 5
          failureThreshold: 3

        # LIVENESS PROBE (wrong path)
        livenessProbe:
          httpGet:
            path: /wronglive
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
